# Arrays
'''
An array is a data structure that contains a group of elements. 
Typically these elements are all of the same data type, such as an integer or string. 

In Python , List is implemented as Dynamic Array , In other languages like JAVA and C++ we have static array and dynamic array. 

# Static Array
In case of static array the size of array is fixed . 
So assume that you made a array with 5 as the capacity and you tried to add more that the capacity then it will through exception : Array Index Out of Order 

# Dynamic Array
In case of Dynamic array , for this you need not to specify any size here you can keep on adding elements.
'''
# Let's take an example . Remember that the Indexing of array starts at 0. 
scores = [30,40,50,60]
print(scores[2])
#the value will be 50 because the indexing starts from 0